spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/edgeserver
    username: edgeserver
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
