spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/edgeserver
    username: edgeserver
  security:
    oauth2:
      resourceServer:
        jwt:
          jwk-set-uri: "http://keycloak:80/realms/toDoListApp/protocol/openid-connect/certs"
cors:
  allowed-origins: "http://34.31.184.204:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
