spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/edgeserver
    username: edgeserver
  security:
    oauth2:
      resourceServer:
        jwt:
          jwk-set-uri: "http://keycloak:80/realms/toDoListApp/protocol/openid-connect/certs"
cors:
  allowed-origins: "http://34.31.184.204:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
gateway:
  ui-uri: https://todolist.ooguy.com
  redirect-host: todolist.ooguy.com
server:
  port: 8093
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: edgeserver
