spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/edgeserver
    username: edgeserver
  security:
    oauth2:
      resourceServer:
        jwt:
          jwk-set-uri: "http://keycloak:80/realms/toDoListApp/protocol/openid-connect/certs"
