spring:
  application:
    name:
      fileprocesor

  kafka:
    streams:
      application-id: file-processor-${random.uuid}
    bootstrap-servers:
      - kafka:9092
    properties:
      default:
        key:
          sarde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          sarde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit:
        interval:
          ms: 3000
      processing:
        quarantee: exactly_once_v2

clamAV:
  url: clamav
  port: 3310
