spring:
  application:
    name: taskmanager
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:80/realms/toDoListApp/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://postgresql:5432/taskmanager
    username: taskmanager
    password: taskmanager_password
    jakarta:
      persistence:
        jdbc:
  liquibase:
    change-log: classpath:/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8094

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

keycloak:
  auth-server-url: http://keycloak
  realm: toDoListApp
  client-id: taskManagerClient
  user-role: USER
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
